<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mlib\Module'                     => __DIR__ . '/Module.php',
    'Mlib\Validator\Validator'        => __DIR__ . '/src/Mlib/Validator/Validator.php',
    'Mlib\Validator\ValidatorConfig'  => __DIR__ . '/src/Mlib/Validator/ValidatorConfig.php',
    'Mlib\Validator\UserConfig'       => __DIR__ . '/src/Mlib/Validator/UserConfig.php',
    'Mlib\Validator\ValidatorFactory' => __DIR__ . '/src/Mlib/Validator/ValidatorFactory.php',
    'Mlib\Form\FormConfig'            => __DIR__ . '/src/Mlib/Form/FormConfig.php',
    'Mlib\Form\Form'                  => __DIR__ . '/src/Mlib/Form/Form.php',
    'Mlib\Form\UserConfig'            => __DIR__ . '/src/Mlib/Form/UserConfig.php',
    'Mlib\Form\Field'                 => __DIR__ . '/src/Mlib/Form/Field.php',
    'Mlib\Data\DataConfig'            => __DIR__ . '/src/Mlib/Data/DataConfig.php',
    'Mlib\Data\Data'                  => __DIR__ . '/src/Mlib/Data/Data.php',
    'Mlib\Data\UserConfig'            => __DIR__ . '/src/Mlib/Data/UserConfig.php',
    'Mlib\Exception\Exception'        => __DIR__ . '/src/Mlib/Exception/Exception.php',
    'Mlib\Model\Base'                 => __DIR__ . '/src/Mlib/Model/Base.php',
    'Mlib\Model\User'                 => __DIR__ . '/src/Mlib/Model/User.php',
    'Mlib\Model\Session'              => __DIR__ . '/src/Mlib/Model/Session.php',
);
