<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mlib\Module'                             => __DIR__ . '/Module.php',
    'Mlib\Validator\Validator'                => __DIR__ . '/src/Mlib/Validator/Validator.php',
    'Mlib\Validator\UserValidatorConfig'      => __DIR__ . '/src/Mlib/Validator/UserValidatorConfig.php',
    'Mlib\Validator\ValidatorConfigInterface' => __DIR__ . '/src/Mlib/Validator/ValidatorConfigInterface.php',
    'Mlib\Validator\ValidatorFactory'         => __DIR__ . '/src/Mlib/Validator/ValidatorFactory.php',
    'Mlib\Form\UserFormConfig'                => __DIR__ . '/src/Mlib/Form/UserFormConfig.php',
    'Mlib\Form\Form'                          => __DIR__ . '/src/Mlib/Form/Form.php',
    'Mlib\Form\Field'                         => __DIR__ . '/src/Mlib/Form/Field.php',
    'Mlib\Form\FormConfigInterface'           => __DIR__ . '/src/Mlib/Form/FormConfigInterface.php',
    'Mlib\Data\Data'                          => __DIR__ . '/src/Mlib/Data/Data.php',
    'Mlib\Data\UserDataConfig'                => __DIR__ . '/src/Mlib/Data/UserDataConfig.php',
    'Mlib\Data\DataConfigInterface'           => __DIR__ . '/src/Mlib/Data/DataConfigInterface.php',
    'Mlib\Exception\Exception'                => __DIR__ . '/src/Mlib/Exception/Exception.php',
    'Mlib\Model\Base'                         => __DIR__ . '/src/Mlib/Model/Base.php',
    'Mlib\Model\User'                         => __DIR__ . '/src/Mlib/Model/User.php',
    'Mlib\Model\Session'                      => __DIR__ . '/src/Mlib/Model/Session.php',
);
